### ISSUE TITLE
Limpieza de variables

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#11]
El encargado de hacer la limpieza de variables debe ser el controlador.
Antes de enviar variables al modelo, estas deben ser validadas y limpiadas.

**Comment by nmicht** [comment]
La limpieza que haces en el modelo, esta bien, esa solo es una limpieza para evitar inyecciones SQL, pero la validación si se debe hacer en el controlador.

**Comment by gabomarin** [comment]
Si se refiere a las variables tales como  un email correcto, teniamos pensado implementar el uso de expresiones regulares que permite html5 en sus formularios

**Comment by nmicht** [comment]
No se pueden fiar a la validación del frontend pues eso se puede brincar
fácilmente.
Deben validar en server también.

**Comment by gabomarin** [comment]
ok entonces haremos esas validaciones

**Comment by lexds1591** [comment]
La validacion de una dirección de un cliente ¿Comó debe ser evaluada?

**Comment by nmicht** [comment]
Caracteres de palabra

**Comment by lexds1591** [comment]
checar issue validaciones
