### ISSUE TITLE
Aplicar transacciones MySQL

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#12]
Al tener queries que dependen de que los anteriores se hayan ejecutado, como en el caso de las facturas, es necesario manejar transacciones.
Te recomiendo leer esto y aplicarlo http://expresionweb.wordpress.com/2009/06/27/transacciones-mysql-con-php/

**Comment by gabomarin** [comment]
Se aplico en las ventas donde se hacian muchas consultas dependientes
