### ISSUE TITLE
Los modelos deberían heredar de la clase de base de datos

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#13]
Si haces que la clase para el manejo de la base de datos sea abstracta y que tus modelos hereden de ella, o que tengas un modelo global del cual hereden todos, facilitará el manejo de la base de datos además de que solo mantendrás una conexión durante toda la ejecución.

**Comment by lexds1591** [comment]
ok suena mejor, es obligatorio implementarlo?

**Comment by nmicht** [comment]
Para entrega final si.

On Tue, Apr 2, 2013 at 10:55 PM, lexds1591 notifications@github.com wrote:

> ok suena mejor, es obligatorio implementarlo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gabomarin/venta_web/issues/13#issuecomment-15818347
> .

## 

_Nancy Michelle Torres Villanueva_
_Consultor TI_
Cel. 33 3394-7423

**Comment by lexds1591** [comment]
ok , entonces lo implementare

**Comment by lexds1591** [comment]
implementado
