### ISSUE TITLE
Error al entrar al sitio

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#14]
![screenshot](http://i.imgur.com/HcP8167.png)

**Comment by lexds1591** [comment]
para nosotros es correcto, porque si no se pone ningun controlador en la url, cae a un caso por default que es el login, y como no esta poniendo ningun dato necesario para el login, es por eso que le da error :D

**Comment by nmicht** [comment]
Pero si el caso es el login debería cargar la vista para el login pues el
usuario tiene que en un form escribir las variables.

**Comment by gabomarin** [comment]
No se supone que los formularios son para la 3ra entrega?
Es que ahi esta cargando el login pero los datos se piden por la url

**Comment by nmicht** [comment]
Si los formularios son en 3ra entrega pero no la estructura.
Y se requiere de una vista antes de enviar variables.

**Comment by gabomarin** [comment]
Entonces que nos recomienda hacer ahi?

**Comment by nmicht** [comment]
Arreglar el controlador.
Pero eso no es importante para entrega dos. Pero si para el final.

**Comment by gabomarin** [comment]
Tenia pensado agregarle un formulario en este caso, pero entonces no hay problema si no alcanzo a  ponerlo hoy?

**Comment by lexds1591** [comment]
Solucionado.

Muestro un mensaje el cual avisa al usuario que faltan variables esperadas
