### ISSUE TITLE
Notice: Undefined index

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#17]
Cuando aparecen estos mensajes, significa que estas intentando utilizar una variable que no ha sido declarada, lo común es que ocurra cuando obtienes variables get o post.

Debes agregar una validación del tipo isset antes de usar estas variables.

Ejemplo del error:

Notice: Undefined index: usuario in /home/cc409/virtualtd/www/controller/usuarioCtl.php on line 59

En el sitio:

http://alanturing.cucei.udg.mx/cc409/virtualtd/?modulo=usuario&action=insertar

**Comment by gabomarin** [comment]
Resuelto, por problemas de mi internet apenas pude cerrar el issue
