### ISSUE TITLE
Tamaño de los inputs pequeño

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#19]
En firefox los inputs del login quedan pequeños y no se ve completo el texto que se esta escribiendo.

**Comment by lexds1591** [comment]
si se refiere a lo alto de ellos, en mi firefox se ve bien. 
![image](https://f.cloud.github.com/assets/3487437/550071/e3c64ed0-c307-11e2-9561-29c2cae58011.png)

**Comment by lexds1591** [comment]
no encontrado
