### ISSUE TITLE
Diseño y creación de la base de datos

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#2]
1. Generar el diseño de la base de datos en diagrama EER. (se recomienda utilizar MySQL Workbench http://www.mysql.com/products/workbench/)
2. Crear la base de datos y obtener las sentencias SQL de la misma
3. Poblar la base de datos con al menos 5 registros en cada tabla, inclusive las tablas que solo registren relaciones.

**Comment by gabomarin** [comment]
Añadido el diagrama y el sql de la creacion

**Comment by nmicht** [comment]
La venta y la factura son tablas distintas? Con que necesidad? Eso no esta especificado en la descripción del proyecto.
Considero mejor mantener el inventario junto con el producto, y por separado mantener una entidad para mermas, en la cual si se indica el producto, las diferencias y quien registra la diferencia.

**Comment by gabomarin** [comment]
La tabla venta y factura son entidades diferentes, por que primero se realiza la venta y después la factura, ademas no siempre se pide factura.  
acerca del  inventario, en las mermas se refiere  a una nueva tabla en la cual almacene los datos de los productos no inventariados?

**Comment by nmicht** [comment]
El inventario se puede mantener en la tabla producto guardando la cantidad
actual.
La tabla inventario sería para registrar en que fecha se hizo el
inventario, cuanto hay de cada cosa, y en caso de no coincidir lo debido
con la realidad, almacenar el motivo de esa merma.

2013/3/11 gabomarin notifications@github.com

> La tabla venta y factura son entidades diferentes, por que primero se
> realiza la venta y después la factura, ademas no siempre se pide factura.
> 
> acerca del inventario, en las mermas se refiere a una nueva tabla en la
> cual almacene los datos de los productos no inventariados?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gabomarin/venta_web/issues/2#issuecomment-14731196
> .

## 

_Nancy Michelle Torres Villanueva_
_Consultor TI_
Cel. 33 3394-7423

**Comment by nmicht** [comment]
1. El usuario debe estar relacionado con la venta, y no con el detalle. La relación además es 1:N
2. La venta debe guardar el total a pagar
3. En producto se debe agregar existencias
4. Generar un tabla para indicar las fechas de inventario, quien las hizo, que producto, cual fue la cantidad que debía haber, cual fue la cantidad real y alguna explicación.
5. ¿En que parte se estan almacenando los privilegios de los usuarios?

**Comment by lexds1591** [comment]
el punto 4 tambien debe aparecer en el Diagrama de clases?

**Comment by gabomarin** [comment]
respecto a los privilegios, teníamos pensado que en el campo tipo del usuario se guardara el tipo de usuario, y en la programacion dependiendo del tipo de usuario tendrian diferentes permisos

**Comment by lexds1591** [comment]
eliminar la tabla inventario, y la tabla detalle inventario renombrarla a inventario y unirla con la de usuario

**Comment by gabomarin** [comment]
hecho, podrias decirme cuales son las cardinalidades que puse mal?

**Comment by lexds1591** [comment]
según yo todas las cardinalidades están al revés, igual ya puedes consultar mi diagrama de clases que ya lo subí completo

**Comment by gabomarin** [comment]
arreglamos las cardinalidades de las tablas y los atributos de ellas, solo tenemos una duda: usted nos recomendo quitar la tabla intermedia entre producto e inventario , pero el workbench al indicarle que entre esas dos tablas su cardinalidad es de muchos a muchos, nos genera  por default una tabla intermedia(ya que esto es lo estandar) , entonces lo dejamos asi?, o aplicamos una diferente cardinalidad para respetar lo que nos menciono la  clase pasada
