### ISSUE TITLE
Validación de formulario login

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#26]
Si ha habido un error al hacer login, se debe indicar, de otra manera no queda claro, pues solo me redirige a la pantalla principal.

**Comment by lexds1591** [comment]
poner el letrerito de que fue invalido el logueo , haciendolo en el controlador

**Comment by lexds1591** [comment]
falta arreglar la posicion del letrero

**Comment by gabomarin** [comment]
Arreglado
