### ISSUE TITLE
Validación de formulario registro

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#27]
Permite un RFC invalido

**Comment by lexds1591** [comment]
cual fue el que probo??? porque mi expresion regular es esta :/^([a-zA-Z]|\d){13}$/
que permite combinacion de numeros y letras obligatoriamente 13

**Comment by nmicht** [comment]
Un RFC tiene reglas, puedes revisarlas aquí: http://es.wikipedia.org/wiki/Registro_Federal_de_Contribuyentes_(M%C3%A9xico)

![pantallazo](http://i.imgur.com/LRt9SB1.png)

**Comment by lexds1591** [comment]
solucionado con la siguiente expresion regular
^[a-zA-Z]{4}(\d){2}((0[1-9])|(1[1-2]))(([1-2]\d)|(3[0-1]))([a-zA-Z]|\d){3}$
