### ISSUE TITLE
Historial de compras

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#29]
Se esta generando mal el historial de compras, pues para un usuario que apenas fue creado me aparece como que ya se han hecho compras.

Revisen el usuario a@a.com

**Comment by lexds1591** [comment]
arreglado, solo falta solucionar el error que obtenemos en el servidor y que cabe destacar que no sucede en nuestro localhost
![image](https://f.cloud.github.com/assets/3487437/627055/eaa734dc-cfee-11e2-9a9c-a655cc443146.png)

**Comment by lexds1591** [comment]
solucionado
