### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#3]
1. Diseñar el diagrama de clases en base a la descripción del proyecto, las notas del profesor y el diagrama EER.

Nota, debe incluir todas las clases requeridas en el sistema!.

**Comment by lexds1591** [comment]
se agrego una imagen con el diagrama de clases

**Comment by nmicht** [comment]
Un diagrama de clases no tiene porque coincidir con un diagrama ER.
Imagina cuantos objetos vas a instanciar del tipo detalle-venta o detalle-inventario.

Este diagrama de clase esta mal por esas dos clases y algunos métodos.
Quién registra el inventario? Es una clase separada de producto?

**Comment by lexds1591** [comment]
en ingeneria del software nos dijeron que debiamos ponerlas, pero las quitare

lo registrar un tipo de usuario que seria como un empleado de la empresa, asi que debo de unir inventario con usuario?

**Comment by nmicht** [comment]
Solo si tu intención es saber que usuario registro el inventario, revisa el
comentario referente a la base de datos.

2013/3/11 lexds1591 notifications@github.com

> en ingeneria del software nos dijeron que debiamos ponerlas, pero las
> quitare
> 
> lo registrar un tipo de usuario que seria como un empleado de la empresa,
> asi que debo de unir inventario con usuario?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gabomarin/venta_web/issues/3#issuecomment-14730558
> .

## 

_Nancy Michelle Torres Villanueva_
_Consultor TI_
Cel. 33 3394-7423

**Comment by nmicht** [comment]
Solo por quemar, ¿quien les dio clase de Ingeniería de software que les enseño que una tabla generado por relación NM es una clase?

**Comment by lexds1591** [comment]
la maestra elsa, aun la estamos llevando, no nos vaya a delatar con ella jajaja

**Comment by lexds1591** [comment]
se le agrego a la clase inventario nuevos campos, se eliminaron las clases intermedias, y se creo la relacion usuario-inventario

**Comment by nmicht** [comment]
1. Creo que falta el modificar completo de producto, no solo el status
2. Falta consultar facturas
3. Podrías hacer un solo método consultar que reciba en los parametros lo que se busca y su valor, o dejarlo asi con muchos métodos

**Comment by lexds1591** [comment]
se corrigió el punto 1 y 2, el 3 lo dejaremos por ahora de esta manera y cuando estemos programando decidiremos cual es mas simple  y/o eficiente.

gracias :D
