### ISSUE TITLE
Errores en diseño responsivo

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#38]
1. El texto de TD-Informatica se sale del div en resolucion de 320
2. Las lineas que separan los productos tambien se salen del div

**Comment by lexds1591** [comment]
320??? es en los moviles???
o como lo probo

**Comment by nmicht** [comment]
Si, en móviles.

Nancy Michelle Torres Villanueva
Consultor TI
33-3394-7423

**Comment by lexds1591** [comment]
implementado
