### ISSUE TITLE
Tareas del encargado del inventario

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#4]
Si es un encargado de inventario, ¿no se supone que entre sus actividades además de listar los inventarios será poder indicar las diferencias?
Es decir, si el ve que deben haber 5 articulos, y solo hay 4, debería poder registrar que se tiene una merma en el inventario.

Es pregunta para que se tome a consideración

**Comment by lexds1591** [comment]
Se agregaron nuevas caracteristicas a el encargado de inventario
