### ISSUE TITLE
Generación de PDF y Excel

### ISSUE THREAD

**Issue by nmicht** [gabomarin/venta_web#40]
El administrador debería poder generar PDF y/o archivos de Excel con estadísticas

**Comment by gabomarin** [comment]
como que tipo de estadisticas?

**Comment by nmicht** [comment]
Por ejemplo listado de productos.
Listado de clientes.
Estadísticas de ventas por mes
Etc

Nancy Michelle Torres Villanueva
Consultor TI
33-3394-7423

**Comment by lexds1591** [comment]
implementado lo de factura
